import { describe, it, expect } from 'vitest';

// Context menu items are generated by ViewportCanvas callbacks.
// We test the logic that determines which items appear.

describe('context menu logic', () => {
  describe('sketch menu items', () => {
    it('shows delete when entity is selected', () => {
      const selectedSketchId = 'line_1';
      const items: { label: string; danger?: boolean }[] = [];
      if (selectedSketchId) {
        items.push({ label: 'Delete', danger: true });
      }
      expect(items).toHaveLength(1);
      expect(items[0]!.label).toBe('Delete');
      expect(items[0]!.danger).toBe(true);
    });

    it('shows construction toggle when entity is selected', () => {
      const selectedSketchId = 'line_1';
      const isConstruction = false;
      const items: { label: string }[] = [];
      if (selectedSketchId) {
        items.push({ label: isConstruction ? 'Toggle Normal' : 'Toggle Construction' });
      }
      expect(items).toHaveLength(1);
      expect(items[0]!.label).toBe('Toggle Construction');
    });

    it('shows normal toggle for construction entities', () => {
      const isConstruction = true;
      const label = isConstruction ? 'Toggle Normal' : 'Toggle Construction';
      expect(label).toBe('Toggle Normal');
    });
  });

  describe('body menu items', () => {
    it('shows empty-space menu when no body is clicked', () => {
      const bodyId = null;
      const isBody = bodyId !== null;
      expect(isBody).toBe(false);
    });

    it('shows body menu when a body is clicked', () => {
      const bodyId = 'body_1';
      const isBody = bodyId !== null;
      expect(isBody).toBe(true);
    });

    it('includes export submenu for body menus', () => {
      const exportFormats = ['STL', 'OBJ', 'STEP'];
      expect(exportFormats).toContain('STEP');
      expect(exportFormats).toContain('STL');
    });
  });

  describe('constraint menu items', () => {
    it('shows horizontal/vertical for lines', () => {
      const entType = 'line';
      const constraints: string[] = [];
      if (entType === 'line') {
        constraints.push('Horizontal', 'Vertical');
      }
      expect(constraints).toContain('Horizontal');
      expect(constraints).toContain('Vertical');
    });

    it('shows fixed for points', () => {
      const entType = 'point';
      const constraints: string[] = [];
      if (entType === 'point') {
        constraints.push('Fix Point');
      }
      expect(constraints).toContain('Fix Point');
    });

    it('shows radius/concentric for circles', () => {
      const entType = 'circle';
      const constraints: string[] = [];
      if (entType === 'circle' || entType === 'arc') {
        constraints.push('Set Radius', 'Concentric');
      }
      expect(constraints).toContain('Set Radius');
      expect(constraints).toContain('Concentric');
    });
  });

  describe('rectangle editing menu', () => {
    it('shows width/height options when a rectangle is detected', () => {
      const rect = { width: 10, height: 5 };
      const items: string[] = [];
      if (rect) {
        items.push(`Set Width (${rect.width})`);
        items.push(`Set Height (${rect.height})`);
      }
      expect(items).toContain('Set Width (10)');
      expect(items).toContain('Set Height (5)');
    });

    it('does not show rectangle options when no rectangle detected', () => {
      const rect = null;
      const items: string[] = [];
      if (rect) {
        items.push('Set Width');
        items.push('Set Height');
      }
      expect(items).toHaveLength(0);
    });
  });

  describe('annotation menu', () => {
    it('shows annotation submenu when annotations exist', () => {
      const annotations = [
        { id: 'ann_1', name: 'Distance', kind: 'distance', value: 10 },
        { id: 'ann_2', name: 'Angle', kind: 'angle', value: 90 },
      ];
      const items = annotations.map((a) =>
        `${a.name}: ${a.kind === 'distance' ? `${a.value} mm` : `${a.value}°`}`
      );
      expect(items).toContain('Distance: 10 mm');
      expect(items).toContain('Angle: 90°');
    });

    it('hides annotation submenu when no annotations', () => {
      const annotations: { id: string }[] = [];
      expect(annotations.length > 0).toBe(false);
    });
  });
});
